"""add guestBook again

Revision ID: 025a9703b456
Revises: aae6e9c729da
Create Date: 2025-06-13 15:13:27.723914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '025a9703b456'
down_revision = 'aae6e9c729da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guest_book',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('guest_name', sa.String(length=100), nullable=False),
    sa.Column('content', sa.String(length=1000), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('guest_book', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guest_book_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest_book', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guest_book_user_id'))

    op.drop_table('guest_book')
    # ### end Alembic commands ###
