"""add guestlist

Revision ID: a28318cee6bd
Revises: fb166b7a4a6a
Create Date: 2025-06-01 23:47:23.545048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a28318cee6bd'
down_revision = 'fb166b7a4a6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guests',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('realname', sa.String(length=100), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=False),
    sa.Column('facebook', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('content', sa.String(length=1000), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('guests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guests_nickname'), ['nickname'], unique=False)
        batch_op.create_index(batch_op.f('ix_guests_phone'), ['phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_guests_user_id'), ['user_id'], unique=False)

    op.create_table('guest_images',
    sa.Column('guest_id', sa.String(length=36), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('guest_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guest_images_guest_id'), ['guest_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guest_images_image_url'), ['image_url'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guest_images_image_url'))
        batch_op.drop_index(batch_op.f('ix_guest_images_guest_id'))

    op.drop_table('guest_images')
    with op.batch_alter_table('guests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guests_user_id'))
        batch_op.drop_index(batch_op.f('ix_guests_phone'))
        batch_op.drop_index(batch_op.f('ix_guests_nickname'))

    op.drop_table('guests')
    # ### end Alembic commands ###
