"""add guestBook

Revision ID: aae6e9c729da
Revises: e9b4636bb1de
Create Date: 2025-06-13 15:10:34.132677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aae6e9c729da'
down_revision = 'e9b4636bb1de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
